import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Factura, FacturaLinea } from '../types';
import { invoiceLegalNote, formatDate, formatEur } from './iva';

const SELLER = {
  name:    'OmniPulse OÜ',
  reg:     'Registry: [REG NUMBER]',
  vat:     'VAT: EE[VAT NUMBER]',
  address: '[Street, City, Estonia]',
  bank:    'IBAN: EE[IBAN] · BIC: [BIC]',
  email:   'billing@omnipulse.eu',
};

export function generateInvoicePDF(factura: Factura, lineas: FacturaLinea[]) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const orange = [255, 140, 0] as const;
  const navy   = [10, 25, 47] as const;
  const gray   = [136, 146, 176] as const;

  // Header background
  doc.setFillColor(...navy);
  doc.rect(0, 0, 210, 45, 'F');

  // Company name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...orange);
  doc.text(SELLER.name, 15, 18);

  // Invoice title
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('INVOICE', 195, 18, { align: 'right' });

  // Seller info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 200);
  doc.text([SELLER.reg, SELLER.vat, SELLER.address, SELLER.bank], 15, 26);

  // Invoice number & dates
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(`Invoice #: ${factura.numero}`, 195, 26, { align: 'right' });
  doc.text(`Date: ${formatDate(factura.fecha_emision)}`, 195, 31, { align: 'right' });
  if (factura.fecha_vencimiento)
    doc.text(`Due: ${formatDate(factura.fecha_vencimiento)}`, 195, 36, { align: 'right' });

  // Divider
  doc.setDrawColor(...orange);
  doc.setLineWidth(0.5);
  doc.line(15, 50, 195, 50);

  // FROM / TO
  doc.setTextColor(...gray);
  doc.setFontSize(8);
  doc.text('FROM', 15, 58);
  doc.text('TO', 110, 58);

  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(SELLER.name, 15, 64);
  doc.text(factura.cliente_nombre || '', 110, 64);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(SELLER.email, 15, 70);

  const clientLines = [
    factura.vat_number ? `VAT: ${factura.vat_number}` : '',
    factura.pais || '',
  ].filter(Boolean);
  if (clientLines.length) doc.text(clientLines, 110, 70);

  // Line items table
  autoTable(doc, {
    startY: 85,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: lineas.map(l => [
      l.descripcion,
      l.cantidad.toString(),
      formatEur(l.precio_unitario),
      formatEur(l.importe),
    ]),
    headStyles: {
      fillColor: [...navy] as [number, number, number],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [245, 247, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { halign: 'center', cellWidth: 20 },
      2: { halign: 'right',  cellWidth: 35 },
      3: { halign: 'right',  cellWidth: 35 },
    },
  });

  // Totals block
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  const totalsX = 130;
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text('Subtotal:', totalsX, finalY);
  doc.text(formatEur(factura.subtotal), 195, finalY, { align: 'right' });

  const legalNote = invoiceLegalNote(factura.tipo_iva);
  if (legalNote) {
    doc.setTextColor(...orange);
    doc.text('VAT (0% – Reverse Charge):', totalsX, finalY + 6);
    doc.text(formatEur(0), 195, finalY + 6, { align: 'right' });
  } else {
    doc.setTextColor(60, 60, 60);
    doc.text(`VAT (${factura.iva_rate}%):`, totalsX, finalY + 6);
    doc.text(formatEur(factura.iva_importe), 195, finalY + 6, { align: 'right' });
  }

  doc.setDrawColor(...orange);
  doc.line(totalsX, finalY + 9, 195, finalY + 9);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text('TOTAL:', totalsX, finalY + 15);
  doc.setTextColor(...orange);
  doc.text(formatEur(factura.total), 195, finalY + 15, { align: 'right' });

  // Payment info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...gray);
  doc.text(`Payment method: ${factura.metodo_pago}`, 15, finalY + 6);
  doc.text(SELLER.bank, 15, finalY + 11);

  // Legal note (reverse charge)
  if (legalNote) {
    const noteY = finalY + 28;
    doc.setFillColor(255, 248, 230);
    doc.roundedRect(15, noteY - 4, 180, 14, 2, 2, 'F');
    doc.setTextColor(180, 80, 0);
    doc.setFontSize(7.5);
    const lines = doc.splitTextToSize(legalNote, 174);
    doc.text(lines, 18, noteY + 1);
  }

  // Footer
  doc.setTextColor(...gray);
  doc.setFontSize(7);
  doc.text(`Generated by OmniPulse OPS · ${new Date().toLocaleDateString('es-ES')}`, 105, 285, { align: 'center' });

  doc.save(`${factura.numero}.pdf`);
}
